config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#index'
  # route GET /check-in to login controller and #index action
  get "checkin", to: "checkin#new"
  post "checkin", to: "checkin#create"
  #appointments page
  get 'appointments', to: "appointments#advisors"
  # scholarships page
  get 'scholarships', to: "scholarships#index"
  # the admin dashboard
  get 'admins', to: 'admins#index'
  get 'view_checkin_records', to: 'admins#view_checkin_records'
  # user routes
  patch 'user', to: 'users#update'
  get 'user/profile/new', to: 'users#profile_new', as: 'user_profile_new'
  patch 'user/profile/update', to: 'users#profile_update', as: 'user_profile_update'
  get 'user/profile/edit', to: 'users#profile_edit', as: 'user_profile_edit'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#google_auth_logout'
  get 'login/confirm', to: 'login#confirm'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  def self.from_omniauth(auth)
    # Creates a new user only if it doesn't exist
    where(email: auth.info.email).first_or_initialize do |user|
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
    end
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def update
    flash.clear
    @user = User.find_by(id: session[:current_user_id])
    if @user.nil?
      redirect_to login_path, flash: { :error => "Please log-in!" }
      return
    end
    first_name = params[:user][:first_name]
    last_name = params[:user][:last_name]
    email = params[:user][:email]
    sid = params[:user][:sid]
    if sid.blank? or sid.length != 10
      redirect_to login_confirm_path, flash: { :error => "Invalid Student ID Number" }
      return
    end
    if @user.update(first_name: first_name, last_name: last_name, email: email, sid: sid)
      redirect_to root_path, flash: { :success => "Success! You've been logged-in!" }
    else
      redirect_to login_confirm_path, flash: { :error => "Something went wrong, please try again." }
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_login

  def update
    flash.clear
    @user = User.find_by(id: session[:current_user_id])
    sid = params[:user][:sid]
    email = params[:user][:email]
    if sid.blank? || (sid.length != 10)
      redirect_to login_confirm_path, flash: { error: 'Invalid Student ID Number.' }
      return
    end
    if email.blank? || !email.match(/.+(@berkeley.edu)/)
      redirect_to login_confirm_path, flash: { error: 'Please use your berkeley email to log-in.' }
      return
    end
    if @user.update(user_params)
      redirect_to user_profile_new_path
    else
      redirect_to login_confirm_path, flash: { error: 'Something went wrong, please try again.' }
    end
  end

  def profile_new
    flash.clear
    @user = Student.find_by_id(session[:current_user_id])
  end

  def profile_update
    skipped = params.key? :skip
    edited = params.key? :submit_edit
    unless skipped
      @user = Student.find_by_id(session[:current_user_id])
      @user.update!(profile_params)
    end
    if edited
      redirect_to root_path, flash: { success: 'Success! Your profile has been updated.' }
    else
      redirect_to root_path, flash: { success: "Success! You've been logged-in!" }
    end
  end

  def profile_edit
    flash.clear
    @user = Student.find_by_id(session[:current_user_id])
  end

  private

  def require_login
    redirect_to root_path, flash: { error: 'Only students have access to profiles.' } unless
      session.key?(:current_user_id) && Student.find_by_id(session[:current_user_id]).present?
  end

  def profile_params
    params.require(:profile).permit(:major, :grad_year, :identities, :pronouns)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :sid)
  end
end

app/views/users/_profile_form.html.erb
<%= form_with method: :patch, url: user_profile_update_path, scope: "profile" do |f| %>
  <div class="row mb-3">
    <div class="col-md-6 offset-md-3">
      <div class="col-md-6 offset-md-3 mb-3">
        <%= f.label :major, class: "form-label" %>
        <%= f.text_field :major, value: @user.major.presence, class: "form-control" %>
        <div id="majorHelp" class="form-text">If you have more than one separate using commas.</div>
      </div>
      <div class="col-md-6 offset-md-3 mb-3">
        <%= f.label :identities, class: "form-label" %>
        <%= f.text_field :identities, placeholder: "LGBTQIA+, First Generation, POC, ...", value: @user.identities.presence, class: "form-control" %>
        <div id="identitiesHelp" class="form-text">Groups/communities that you identify with.</div>
      </div>
      <div class="col-md-6 offset-md-3 mb-3">
        <%= f.label :grad_year, class: "form-label" %>
        <%= f.date_select :grad_year, {:selected => @user.grad_year.presence, :order => [:year], :start_year => Time.now.year, :end_year => Time.now.year + 15, :prompt => {:year => "Select year"}}, {:class => "form-select form-select-md mb-3s"} %>
        <div id="gradYearHelp" class="form-text">Your expected graduation year.</div>
      </div>
      <div class="col-md-6 offset-md-3 mb-3">
        <%= f.label :pronouns, class: "form-label"  %>
        <%= f.text_field :pronouns, placeholder: "They/Them/Theirs", value: @user.pronouns.presence, class: "form-control" %>
        <div id="pronounsHelp" class="form-text">Your pronouns.</div>
      </div>
      <div class="form-text">Keep in mind, all of these fields are entirely <b>optional</b>.</div>
    </div>
    <div class="col-md-6 offset-md-3">
      <% if params[:edit_profile] %>
        <%= link_to "Back", root_path, class: "btn btn-secondary btn-lg ms-2 my-4", style:"color:#003262" %>
        <%= f.submit "Submit", name: "submit_edit", class: "btn btn-primary btn-lg ms-2 my-4 berkeley-color", style:"border-color:#003262"  %>
      <% else %>
        <%= f.submit "Skip", name: "skip", class: "btn btn-secondary btn-lg ms-2 my-4"  %>
        <%= f.submit "Submit", name: "submit", class: "btn btn-primary btn-lg ms-2 my-4"  %>
      <% end %>
    </div>
<% end %>
</div>

app/views/users/profile_edit.html.erb
<nav class="navbar navbar-expand-sm navbar-light berkeley-color">
  <div class="container">
    <%= link_to "Home", root_path, method: :get, class: "btn btn-outline-primary", style: "color: grey; border-color: grey;"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav" aria-label="Expand Navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Check In".html_safe, checkin_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Make Appointments".html_safe, appointments_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Scholarships".html_safe, scholarships_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Courses".html_safe, courses_path, class: "nav-link", style:"color: grey;"%>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <div class="<%= flash.empty? ? 'px-4 py-5 my-2 text-center' : 'px-4 pb-5 mb-5 text-center' %>">
    <%= render "shared/flash_messages" %>
    <h1 class="display-5 fw-bold pb-3">Edit Your Profile &#x1f4dd</h1>
    <%= render 'profile_form' %>
  </div>
</div>

app/views/users/profile_new.html.erb
<nav class="navbar navbar-expand-sm navbar-light berkeley-color">
  <div class="container">
    <%= link_to "Home", root_path, method: :get, class: "btn btn-outline-primary", style: "color: grey; border-color: grey;"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav" aria-label="Expand Navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Check In".html_safe, checkin_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Make Appointments".html_safe, appointments_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Scholarships".html_safe, scholarships_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Courses".html_safe, courses_path, class: "nav-link", style:"color: grey;"%>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <div class="<%=flash.empty? ? 'px-4 py-5 my-2 text-center' : 'px-4 pb-5 mb-5 text-center' %>">
    <%= render "shared/flash_messages" %>
    <h1 class="display-5 fw-bold pb-3">Let's get to know you a bit more...</h1>
    <p class="h2 mb-3">You can fill out this information now, or at a later time &#x1f557</p>
    <%= render 'profile_form' %>
  </div>
</div>