config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#index'
  # route GET /check-in to login controller and #index action
  get "checkin", to: "checkin#new"
  post "checkin", to: "checkin#create"
  #appointments page
  get 'appointments', to: "appointments#advisors"
  # scholarships page
  get 'scholarships', to: "scholarships#index"
  # the admin dashboard
  get 'admins', to: 'admins#index'
  get 'view_checkin_records', to: 'admins#view_checkin_records'
  # user routes
  patch 'user', to: 'users#update'
  get 'user/profile/new', to: 'users#profile_new', as: 'user_profile_new'
  patch 'user/profile/update', to: 'users#profile_update', as: 'user_profile_update'
  get 'user/profile/edit', to: 'users#profile_edit', as: 'user_profile_edit'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#google_auth_logout'
  get 'login/confirm', to: 'login#confirm'
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :staff
  belongs_to :student, optional: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :require_login

    def advisors
    end

    def require_login
        unless session.has_key? :current_user_id and Student.find_by_id(session[:current_user_id])
          redirect_to root_path, flash: { error: "Please log in first!" }
        end
    end
      
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment_table.html.erb
<table class="table table-striped col-md-12" id="<%= tid %>">
  <thead>
    <tr>
      <th>Time</th>
      <th>Counselor name</th>
      <th>More info</th>
    </tr>
  </thead>
  <tbody>
    <% appointments.each do |appts| %>
      <tr>
        <td>
          <%= appts.time.strftime("%Y-%m-%d %H:%M") %>
        </td>
        <td>
          <%= appts.staff.name %>
        </td>
        <td>
          <%= link_to "more info".html_safe, appointment_path(id: appts.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/advisors.html.erb
<nav class="navbar navbar-expand-sm navbar-light berkeley-color">
  <div class="container">
    <%= link_to "Home", root_path, method: :get, class: "btn btn-outline-primary", style: "color: grey; border-color: grey;"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav" aria-label="Expand Navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Check In".html_safe, checkin_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Make Appointments".html_safe, '#', method: :get, class: "nav-link", style:"color: white;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Scholarships".html_safe, scholarships_path, class: "nav-link", style:"color: grey;"%>
        </li>
        <li class="nav-item">
          <%= link_to "Courses".html_safe, courses_path, class: "nav-link", style:"color: grey;"%>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container ">
<br></br><h1 class="display-5 fw-bold" align = "center" style = "color: #003262">Make an Appointment with a Counselor</h1><br></br>
    <div class="row">
      <br></br><p class="lead mb-4" align="center">Amanda</p>
      <iframe class="col-lg-12 col-md-12 col-sm-12" src="https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUFTcERNeEp2clFNfGRlZmF1bHR8NGE3NmY4OTQ2ZWE5MTM3MTViYzM0ZWE1YTM3ZjE1NWU" height="500" width="500" align = "center">
          this is an iframe
      </iframe>
      <br></br><p class="lead mb-4" align="center">Trinh</p>
      <iframe class="col-lg-12 col-md-12 col-sm-12" src="https://trinh.youcanbook.me/" height="500" width="300" alight = "center">
          this is an iframe
      </iframe>
      </div>
      <hr class="col mt-5 mx-auto"/>
      <div class="col-lg-6 mt-5 mx-auto" align="center">
        <%= link_to "Back", root_path, method: :get, class:"btn btn-secondary btn-lg my-4", style:"color:#003262" %>
      </div>
      </div>
</div>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="container">
  <div class="<%=flash.empty? ? 'px-4 py-5 my-2' : 'px-4 pb-5 mb-5' %> text-center">
    <% flash.each do |type, msg| %>
      <div class="<%=type.to_s === "success" ? 'alert alert-success mt-2 mb-4' : 'alert alert-danger mt-2 mb-4'%>">
        <%= msg.html_safe %>
      </div>
    <% end %>
    <h1 class="display-5 fw-bold">Appointment Page</h1>
    </br>
    <h3 class="text-start fw-bold">Upcoming Appointments</h3>
    <% if @upcoming.size == 0 %>
      <p class="lead mb-4">You don't have any upcoming appointment!</p>
    <% else %>
      <%= render "appointment_table", tid: "upcoming_appointments", appointments: @upcoming %>
    <% end %>

    <% if @user.is_student %>
      <%= link_to "Book a new appointment".html_safe, appointments_student_profile_check_path, class: "btn btn-primary mt-1 btn-lg px-4 gap-3" %>
    <% end %>

    <h3 class="text-start fw-bold">Past Appointments</h3>
    <% if @past.size == 0 %>
      <p class="lead mb-4">You don't have any appointment before!</p>
    <% else %>
      <%= render "appointment_table", tid: "past_appointments", appointments: @past %>
    <% end %>
    <%= link_to "view all past appointments".html_safe, view_all_past_appointments_path(page: 1) %>
  </div>
  
  <div class="text-left">
    <%= link_to "back to landing page".html_safe, root_path, class: "btn btn-secondary mt-1 btn-lg px-4 gap-3" %>
  </div>
</div>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/student_profile_check.erb
<a>Here is appointment student profile check page</a>

app/views/appointments/view_all_past_appointments.html.erb
<div class="container">
  <div class="<%=flash.empty? ? 'px-4 py-5 my-2' : 'px-4 pb-5 mb-5' %> text-center">
    <% flash.each do |type, msg| %>
      <div class="<%=type.to_s === "success" ? 'alert alert-success mt-2 mb-4' : 'alert alert-danger mt-2 mb-4'%>">
        <%= msg.html_safe %>
      </div>
    <% end %>
    <h1 class=" display-5 fw-bold">Past Appointments</h1>
    <%= render "appointment_table", tid: "all_past_appointments", appointments: @past_appointments %>
    <div class = "move-page">
      <%= link_to "previous page".html_safe, view_all_past_appointments_path(page: params[:page].to_i - 1),
      class: "btn btn-secondary mt-1 btn-lg px-4 gap-3 #{params[:page].to_i <= 1 ? 'disabled' : nil}" %>
      <%= link_to "next page".html_safe, view_all_past_appointments_path(page: params[:page].to_i + 1), 
        class: "btn btn-secondary mt-1 btn-lg px-4 gap-3 text-right #{!@has_next_page ? 'disabled' : nil}" %>
    </div>
  </div>
  
  <div class="text-left">
    <%= link_to "back to appointment page".html_safe, appointments_path, class: "btn btn-secondary mt-1 btn-lg px-4 gap-3" %>
  </div>
</div>